version: "3"

services:
  database:
    image: postgres:12.1-alpine

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
      POSTGRES_DB: micro_cinema

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  cinema:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD-postgres}@database/micro_cinema

    depends_on:
      - database

    volumes:
      - ./config.yaml:/usr/src/app/config.yaml
      - ./account:/usr/src/app/account
      - ./movies:/usr/src/app/movies
