version: "3"

services:
  database:
    image: postgres:12.1-alpine

    environment:
      POSTGRES_PASSWORD: ${POSRGRES_PASSWORD}
      POSTGRES_DB: micro_cinema

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  cinema:
    build:
      context: ./api/
      dockerfile: Dockerfile

    environment:
      DATABASE_URL: postgresql://postgres:${POSRGRES_PASSWORD}@postgres/micro_cinema

    depends_on:
      - database

    volumes:
      - ./data/cinema:/usr/src/app/data
